default:
    trainer: sac
    batch_size: 32
    beta: 0.00455000018700957
    buffer_size: 1000000
    buffer_init_steps: 1000
    init_entcoef: 0.1
    train_interval: 3
    vis_encode_type: simple
    epsilon: 0.216
    hidden_units: 64
    lambd: 0.9144
    learning_rate: 0.000155999994603917
    tau: 0.005
    max_steps: Infinity
    memory_size: 64
    normalize: True
    num_epoch: 3
    num_layers: 3
    num_update: 1
    time_horizon: 32
    sequence_length: 16
    summary_freq: 4000
    use_recurrent: True
    reward_signals:
        extrinsic:
            strength: 1
            gamma: 0.99
    curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256

