version: "3.7"

services:
    unitystation:
        build: .
        image: unitystation/unitystation
        environment: 
            RCON_PASSWORD: 1234
        ports:
            - 7777:7777
            - 7778:7778
